### ISSUE TITLE
Error loading libfuse on Ubuntu runners

### ISSUE THREAD

**Issue by marcosvafilho** [mfinelli/setup-imagemagick#242]
Hi,

Not sure if it's a problem with this action or with the github runner, but suddenly I am unable to use the action due to a dependency on FUSE, which actually looks like a dependency of AppImage (?).

<img width="455" alt="image" src="https://user-images.githubusercontent.com/6841003/206246607-091ed9cb-8270-4d2a-b097-ab460b4fb9d6.png">

Any idea about what is happening? Did github changed anything in their Ubuntu runners?

<img width="730" alt="image" src="https://user-images.githubusercontent.com/6841003/206248800-a394a201-516d-4cad-b18e-392a3fa4b2fe.png">

My best, thanks ;)

**Comment by mfinelli** [comment]
Hi @marcosvafilho sorry for the late response. The problem is that Github updated the default `ubuntu-latest` runner to 22.04 which no longer ships `libefuse2` by default which you've correctly noted is an `AppImage` problem.

Until AppImage is updated to either support a static fuse2 or switch to fuse3 (there are various issues linked on the https://github.com/AppImage/AppImageKit/issues project) you have a couple of options (in no particular order):

- Switch your workflows to use `ubuntu-20.04`
- Manually install `libfuse2` when running on `ubuntu-latest` or `ubuntu-22.04`, e.g.:
  ```yaml
  - uses: mfinelli/setup-imagemagick@v2
  - run: sudo apt-get install -y libfuse2
  - run: magick....
  ```

I'll update the readme to mention this in the next few days
